# Experiment settings to train/test a 3 hidden layer Neural Net on 
# Caltech flyvfly dataset

!obj:experiments.FitPredictErrorExperiment {

  dataset: &ds !obj:flyvfly.Fly {
    repo_path: '~/data',
    sample_pct: 100,
  },

  metrics: {
    train: [
      !obj:metrics.MisclassPercentage {},
    ],
    test: [
      !obj:metrics.MisclassPercentage {},
    ],
  },

  predictions: ["train", "test"],

  weight_init: &wt_init !obj:params.UniformValGen {
    low: -1,
    high: 1,
    bias_init: 0.1,
  },

  lrule: &gdm {
    type: gradient_descent_momentum,
    lr_params: {
      learning_rate: 0.1,
      momentum_params: {
        type: constant,
        coef: 0,
      },
    },
  },
  # simple MLP model specification
  model: !obj:models.MLP {
    num_epochs: 2500,
    batch_size: &bs 30,
    layers: [
      &datalayer !obj:layers.DataLayer {
        name: d0,
        nout: 510,
      },
      !obj:layers.FCLayer {
        name: h0,
        nout: 1000,
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:transforms.RectLin {},
      },
      &lastlayer !obj:layers.FCLayer {
        name: output,
        nout: 1,
        lrule_init: *gdm,
        weight_init: *wt_init,
        activation: !obj:transforms.Logistic {},
      },
      &costlayer !obj:layers.CostLayer {
        name: cost,
        ref_layer: *datalayer,
        cost: !obj:transforms.CrossEntropy {},
      },
    ],
  },

  # logging options that are passed to logging.basicConfig
  # level value thresholds (set level lower to display them):
  #   CRITICAL 50
  #   ERROR    40
  #   WARNING  30
  #   INFO     20
  #   DEBUG    10
  #   NOTSET    0
  logging: {
    level: 20,
    format: '%(asctime)-15s %(levelname)s:%(module)s - %(message)s'
  },
}
